on: [push]

name: CI for 'sockets-and-pipes' library

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc:
          - '8.10.1'
          - '8.8.1'

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Build
        run: cabal build
